---

fail_fast: false
minimum_pre_commit_version: "4.0.1"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/bandit
    rev: 2d0b675b04c80ae42277e10500db06a0a37bae17  # frozen: 1.8.6
    hooks:
      - id: bandit
        description: 'Bandit is a tool for finding common security issues in Python code'
        additional_dependencies: [ "bandit[toml]" ]
        args: ["-c", "pyproject.toml"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 3d44372123ca5e8617fdb65d9f11facd159b9e95  # frozen: v0.12.3
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

  - repo: https://github.com/psf/black
    rev: 8a737e727ac5ab2f1d4cf5876720ed276dc8dc4b  # frozen: 25.1.0
    hooks:
      - id: black
        language_version: python3.13
