name: 'Publish Release'

on:
  push:
    tags:
      - '*'

env:
  EXIT_ON_PUBLISH_FAILURE: 1

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: write
      discussions: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          fetch-depth: 0

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@d9e0f98d3fc6adb07d1e3d37f3043649ddad06a1  # v6.5.0
        with:
          enable-cache: true
          python-version-file: .python-version

      - name: Verify Versions Match
        run: |
          TAG_VERSION=$(git describe HEAD --tags --abbrev=0)
          MODULE_VERSION=$(uv version)
          echo "Git Tag Version: $TAG_VERSION"
          echo "Python Module Version: $MODULE_VERSION"
          if [[ "genai-processors-url-fetch $TAG_VERSION" != "$MODULE_VERSION" ]]; then exit 1; fi
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV

      - name: Build Package
        run: uv build

      - name: Publish to PyPi
        run: uv publish || exit $EXIT_ON_PUBLISH_FAILURE

      - name: Release
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836  # v2.3.3
        with:
          discussion_category_name: announcements
          generate_release_notes: true
          files: |
            dist/genai_processors_url_fetch-${{env.TAG_VERSION}}.tar.gz
            dist/genai_processors_url_fetch-${{env.TAG_VERSION}}-py3-none-any.whl
